第18章例題問題追加
shunji-yamaguchi/javaStudy pull request #17
Opened 2017-05-08 06:39 UTC by shunji-yamaguchi

第18章を追加いたしました。chapter18/problemに章末問題が入っています。

よろしくお願い致します。

2017-05-09 00:23 UTC, fossamagna requested changes

2017-05-09 00:23 UTC, fossamagna commented on chapter18/problem/Prime1.java
> +            writer.close();
`close()`は`finally`ブロックに記述したほうがいいですね。

2017-05-09 00:23 UTC, fossamagna commented on chapter18/example/WriteFile1.java
> +            writer.close();
`reader.close()`で例外が発生しても`writer.close()`が呼ばれるようにするにはどうしたらいいでしょうか？

2017-05-09 00:23 UTC, fossamagna commented on chapter18/example/FileDump1.java
> +                in.close();
`finally`ブロックで呼び出したほうがより最後にやりたい処理だということが明確になると思います。

2017-05-09 04:13 UTC, shunji-yamaguchi commented
修正いたしました、よろしくお願い致します。

2017-05-09 04:16 UTC, sakai-y commented on chapter18/example/outputRe.txt
> +            System.out.println("使用法：java WriteFile1 作�?�ファイル");
なんか化けてる

2017-05-09 04:16 UTC, sakai-y commented on chapter18/example/FileDump1.java
> +    public static String byteToHexString(byte b) {
`String.format()`を使うと楽に。

2017-05-09 04:16 UTC, sakai-y commented on chapter18/example/RenameFile1.java
> +        String oldfilename = args[0];
変数名はcamelCaseにしましょう。この場合`oldFilename`

2017-05-09 05:34 UTC, shunji-yamaguchi commented
修正いたしました、よろしくお願い致します。

2017-05-09 05:36 UTC, sakai-y approved these changes
LGTM

2017-05-10 00:18 UTC, fossamagna approved these changes
LGTM

2017-05-11 08:34 UTC, t-kunou commented on chapter18/problem/FindFile1.java
> +            while ((line = reader.readLine()) != null) {
for文にすると少し短く出来るかも

```java
for (int lineNum = 1; (line = reader.readLine()) != null; lineNum++) {
```

2017-05-11 08:44 UTC, shunji-yamaguchi commented
修正いたしました、よろしくお願い致します。

2017-05-11 08:46 UTC, t-kunou commented
👍 ⭐️

2017-05-12 01:09 UTC, merged