第19章例題問題追加
shunji-yamaguchi/javaStudy pull request #18
Opened 2017-05-09 08:49 UTC by shunji-yamaguchi

第19章を追加いたしました。chapter19/problemに章末問題が入っています。

よろしくお願い致します。

2017-05-09 09:38 UTC, sakai-y requested changes

2017-05-09 09:38 UTC, sakai-y commented on chapter19/problem/MyStringArrayList.java
> +    public void add(String s) {
- 容量が十分なら末尾に追加
- 容量不足なら拡張して末尾に追加

と実装されていますが、拡張したら容量は十分なはずなので・・・。

2017-05-09 09:38 UTC, sakai-y commented on chapter19/problem/MyStringArrayListTest.java
> +        ar = (String[])getPrivateField(msa, "ar");
`ar`を取得するメソッドも用意した方がよさそうですね。

2017-05-09 09:38 UTC, sakai-y commented on chapter19/problem/MyStringArrayListTest.java
> +    public void 負の数でgetするとIndexOutOfBoundsExceptionを投げる() {
さっそく例外をテストすることになりましたね。
`@Test(例外クラス)`と書くことで期待する例外をテストできます。

2017-05-10 01:13 UTC, shunji-yamaguchi commented
修正いたしました、よろしくお願い致します。

2017-05-10 04:36 UTC, sakai-y commented on chapter19/problem/MyStringArrayListTest.java
> +    public static String[] getAr(Object target) throws Exception {
これと次のメソッドは外部公開すべきでしょうか。

2017-05-10 08:14 UTC, shunji-yamaguchi commented on chapter19/problem/MyStringArrayListTest.java
> +    public static String[] getAr(Object target) throws Exception {
このクラス内でしか使用しないのですべきでないと思います。
privateに修正します。

2017-05-10 08:19 UTC, shunji-yamaguchi commented
修正いたしました、よろしくお願い致します。

2017-05-10 08:32 UTC, sakai-y approved these changes
LGTM

2017-05-11 10:06 UTC, t-kunou commented
良さそうです ⭐️

2017-05-24 00:07 UTC, fossamagna approved these changes
LGTM

2017-05-24 04:30 UTC, merged