第8章例題問題追加
shunji-yamaguchi/javaStudy pull request #7
Opened 2017-04-24 06:07 UTC by shunji-yamaguchi

第8章を追加いたしました。chapter08/problemに章末問題が入っております。
よろしくお願い致します。

2017-04-24 08:46 UTC, sakai-y requested changes

2017-04-24 08:46 UTC, sakai-y commented on chapter08/problem/Problem8_2.java
> +
問題文でも、ここ２行ですか？

2017-04-24 08:46 UTC, sakai-y commented on chapter08/problem/Problem8_5.java
> +    public static String[] getYourName() {
引数に代入して返して・・・ませんね。

2017-04-25 01:03 UTC, shunji-yamaguchi commented
修正しました、よろしくお願い致します。

2017-04-25 01:29 UTC, sakai-y approved these changes
LGTM

2017-04-25 01:33 UTC, t-kunou commented on chapter08/problem/Problem8_5.java
> +    public static void getYourName(String[] name) {
L11に書いてあるように引数のStringに代入してもうまく動かず、ここのように引数の配列に入れると期待通り動いていると思いますが、なぜでしょうか？
（この辺のことは書籍に書いてあるんですかね）

2017-04-25 01:56 UTC, shunji-yamaguchi commented on chapter08/problem/Problem8_5.java
> +    public static void getYourName(String[] name) {
Stringは基本型なので引数として変数を渡すと、それが引数で宣言された変数に代入されます。これは元の変数とは無関係なので、変更があっても元の変数に影響はありません。
配列は参照型なので引数として渡すと、その配列の参照先が引数で宣言された変数に代入されます。そのためどちらかに変更があると、参照先が同じなので互いに影響を受けます。
だと思います。

書籍でも基本型と参照型の違いやメソッドについて丁寧に説明されています。

2017-04-25 01:59 UTC, t-kunou commented
良いと思います 🌟

2017-04-25 02:03 UTC, t-kunou commented on chapter08/problem/Problem8_5.java
> +    public static void getYourName(String[] name) {
>  その配列の参照先が引数で宣言された変数に代入

厳密にいうと、その配列と参照先が同じシャローコピーが代入される、ですかね

2017-04-25 02:12 UTC, t-kunou commented on chapter08/problem/Problem8_5.java
> +    public static void getYourName(String[] name) {
あれ…よく読むと…？
書籍で言っている基本型が何を指しているかわからないですが、Stringはプリミティブ型ではないですよ…

2017-04-25 02:27 UTC, shunji-yamaguchi commented on chapter08/problem/Problem8_5.java
> +    public static void getYourName(String[] name) {
Stringも参照型でした。勘違いしておりました。

String型は参照型なので、引数として渡した変数と引数で宣言された変数は同じ文字列を参照している。しかし、Stringはイミュータブルなオブジェクトで生成した後に変化させることができない。そのため変更する場合は、新しく別の文字列を作ってそれを参照するようになる。そのたため変更後は参照先が元の変数と別になり、元の文字列に影響はない。
で合ってますでしょうか。

2017-04-25 02:55 UTC, t-kunou commented on chapter08/problem/Problem8_5.java
> +    public static void getYourName(String[] name) {
良いとおもます 🙆 🆗 👍 

補足すると、単純な代入は変数が指しているオブジェクトを差し替えるだけで、参照先のオブジェクトの状態は変更されません。オブジェクトの状態が変わる操作をすると呼び出し元にも影響しますが、↑で書かれた通り、Stringはイミュータブルなのでオブジェクトの状態を変えることができません。（添字付きで配列に代入した場合は、配列の要素を差し替えているのでオブジェクトの状態変更にあたります）

なお、引数で受け取ったオブジェクトの状態を変更するのは ``破壊的代入`` と呼ばれ、パフォーマンス等で仕方がない場合を除くと悪いコードの典型として指摘を受けると思います。

2017-04-25 07:01 UTC, fossamagna approved these changes
LGTM

2017-04-25 08:24 UTC, merged